# $OpenBSD$

COMMENT =		no-operation command for Jim

DISTNAME =		jimnop_cmd-0.1
CATEGORIES =		devel
HOMEPAGE =		http://www3.bell.net/stwo/
MAINTAINER =		Stuart Cassoff <stwo@users.sourceforge.net>

# ISC
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB	=		jim

GH_ACCOUNT =		aryler
GH_PROJECT =		Jimnop_cmd
GH_TAGNAME =		0.1

BUILD_DEPENDS =		lang/jimtcl
RUN_DEPENDS =		lang/jimtcl
SEPARATE_BUILD =	Yes
CONFIGURE_STYLE =	simple

.include <bsd.port.mk>
